import {chromium} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const state=JSON.parse(await readFile('/tmp/vt-depth3-state.json','utf8')),out='/tmp/vt-depth3-independent';await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const errors=[];try{
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/state',r=>r.fulfill({json:state}));await page.goto('http://127.0.0.1:8107/client/');await page.getByRole('button',{name:'Mapa',exact:true}).click();await page.getByText('Mapa 3D',{exact:true}).click();await page.locator('.world-3d-host canvas,.visual-3d canvas').first().waitFor();await page.waitForTimeout(700);await page.screenshot({path:out+'/desktop-before.png'});
const before=await page.locator('.visual-3d').innerHTML();await page.getByRole('button',{name:'Acercar mapa 3D',exact:true}).click();await page.getByRole('button',{name:'Rotar mapa 3D',exact:true}).click();await page.waitForTimeout(300);const after=await page.locator('.visual-3d').innerHTML();if(before===after)throw Error('Projected labels unchanged after zoom/rotation');await page.screenshot({path:out+'/desktop-rotated.png'});await page.getByRole('button',{name:'Centrar mapa 3D',exact:true}).click();
const canvas=page.locator('.visual-3d canvas').first();const box=await canvas.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.55,{steps:5});await page.mouse.up();await page.screenshot({path:out+'/desktop-drag.png'});
await page.setViewportSize({width:393,height:750});await page.screenshot({path:out+'/mobile-map.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);await page.setViewportSize({width:320,height:740});await page.screenshot({path:out+'/mobile320-map.png',fullPage:true});await page.getByRole('button',{name:'Personaje',exact:true}).click();await page.getByRole('button',{name:/Ver representación de/}).click();await page.getByText('Ver miniatura 3D',{exact:true}).click();await page.locator('dialog canvas').waitFor();await page.waitForTimeout(300);await page.screenshot({path:out+'/mobile-figure.png'});await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'detached'});
await writeFile(out+'/report.json',JSON.stringify({errors,overflow,knownNodes:state.map.nodes.length,rendered:true,zoomRotationChangedLabels:true,dragExercised:true,figureRendered:true},null,2));console.log(JSON.stringify({errors,overflow,knownNodes:state.map.nodes.length,out}));
}finally{await browser.close();}
