import json
from pathlib import Path
from playwright.sync_api import sync_playwright
OUT=Path(__file__).resolve().parent;snapshot=json.loads((OUT/'snapshot.json').read_text());nodes=[n for n in snapshot['map']['nodes'] if n['id'].startswith('valdren_')][:10];ids={n['id'] for n in nodes};snapshot['map']['nodes']=nodes;snapshot['map']['routes']=[r for r in snapshot['map']['routes'] if r['from'] in ids and r['to'] in ids];snapshot['map']['edges']=[e for e in snapshot['map']['edges'] if set(e if isinstance(e,list) else [e['from'],e['to']])<=ids]
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True);page=b.new_page(viewport={'width':393,'height':950});page.route('**/api/state',lambda r:r.fulfill(json=snapshot));page.goto('http://127.0.0.1:8121');page.wait_for_load_state('networkidle');page.get_by_role('button',name='Mapa',exact=True).click();page.get_by_role('button',name='Ver todo lo descubierto',exact=True).click();page.wait_for_timeout(150)
 m=page.locator('.discovered-map').evaluate('(e)=>({width:e.clientWidth,height:e.clientHeight,scale:new DOMMatrix(getComputedStyle(e).transform).a})');xs=[n['position'][0] for n in nodes];ys=[n['position'][1] for n in nodes]
 expected=page.evaluate("async()=>{const u=await import('/client/ui-data.js'),s=await(await fetch('/api/state')).json(),map=u.orientationMap(s.map,s.character.location),positions=u.discoveredLayout(map),cells=[...positions.values(),...u.discoveredPaths(map,positions).flatMap(l=>l.points.map(p=>p.map(v=>v/4)))];return {width:(Math.max(...cells.map(p=>p[0]))-Math.min(...cells.map(p=>p[0])))*230+164,height:(Math.max(...cells.map(p=>p[1]))-Math.min(...cells.map(p=>p[1])))*170+132};}");assert abs(m['width']-expected['width'])<=1;assert abs(m['height']-expected['height'])<=1;assert m['height']<1500;assert m['scale']>.2

 page.locator('.discovered-panel').screenshot(path=str(OUT/'393-partial-valdren.png'));(OUT/'partial-report.json').write_text(json.dumps({'scope':'Partial 10-room Valdren display fixture; stable absolute server positions, only visited room extent used','status':'PASS','nodes':len(nodes),'bounds':m,'worldY':[min(ys),max(ys)]},indent=2));print(m);b.close()
