import {chromium} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';
import {readFile,readdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const rooms={};for(const file of await readdir('content/regions'))if(file.endsWith('.json'))Object.assign(rooms,JSON.parse(await readFile('content/regions/'+file,'utf8')).rooms);
const base='http://127.0.0.1:8098',browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']}),results=[];
try{for(const width of [1440,393,320]){
 const ctx=await browser.newContext({viewport:{width,height:900}}),dm=await browser.newContext(),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const state=async()=> (await ctx.request.get(base+'/api/state')).json();
 const post=async(context,path,data)=>{const s=await(await context.request.get(base+'/api/state')).json();const r=await context.request.post(base+path,{data:{...data,csrf_token:s.csrf_token}});assert.ok(r.ok(),await r.text());return r.json()};
 const act=(id,target)=>post(ctx,'/api/action',{id,target,request_id:crypto.randomUUID()});
 await post(ctx,'/api/account/register',{username:'honing'+Date.now()+width,password:'isolated-password'});const created=await post(ctx,'/api/character/create',{name:'Prueba afinado',species:'dravak',class_id:'juramentado'});
 await post(dm,'/api/master/login',{password:'isolated-review-only'});await post(dm,'/api/master/approve',{character_id:created.character.id});for(let step=0;step<6;step++)await post(ctx,'/__isolated/advance',{seconds:300});await act('mover','salir');
 async function walk(dest){const start=(await state()).room.id,q=[[start,[]]],seen=new Set([start]);let path;while(q.length){const [here,steps]=q.shift();if(here===dest){path=steps;break}for(const [dir,to]of Object.entries(rooms[here].exits))if(!seen.has(to)){seen.add(to);q.push([to,[...steps,dir]])}}assert.ok(path);for(const dir of path)await act('mover',dir)}
 await walk('korven_loma_cascajo');await act('buscar');await walk('korven_taller_juntas');const before=await state(),weapon=before.inventory.find(i=>i.kind==='weapon'),material=before.inventory.find(i=>i.catalog_id==='piedra_veteada'||i.id==='piedra_veteada');assert.ok(material);
 await page.goto(base);await page.getByRole('button',{name:'Mochila',exact:true}).click();const offer=page.getByRole('button',{name:/Afinar Espada de juramento/});assert.equal(await offer.count(),1);assert.ok((await offer.innerText()).includes('Consume 1 Piedra veteada'));
 let dialogText='';page.once('dialog',async d=>{dialogText=d.message();await d.dismiss()});await offer.click();assert.ok(dialogText.includes('daño base 10 → 11'));assert.ok(dialogText.includes('12 sellos y 1 Piedra veteada'));assert.equal((await state()).character.seals,before.character.seals);assert.equal((await state()).inventory.find(i=>i.id===weapon.id).damage,weapon.damage);
 await page.screenshot({path:`review/honing-confirmation/${width}.png`});page.once('dialog',d=>d.accept());await offer.click();await page.getByText('Afinada · +1 daño',{exact:true}).waitFor();const after=await state();assert.equal(after.character.seals,before.character.seals-12);assert.equal(after.inventory.find(i=>i.id===weapon.id).damage,weapon.damage+1);const left=after.inventory.find(i=>i.id===material.id)?.quantity||0;assert.equal(left,material.quantity-1);assert.equal(await page.getByRole('button',{name:/Afinar Espada/}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 results.push({width,materialVisible:true,dialog:dialogText,cancelPreservesState:true,acceptedCost:12,damageBefore:10,damageAfter:11,materialConsumed:1,repeatOfferRemoved:true,errors});await ctx.close();await dm.close();
}await writeFile('review/honing-confirmation/browser.json',JSON.stringify({scope:'Real browser against isolated HTTP server 8098; new level1 characters; material found through ordinary search; no production writes or seeded inventory. Isolated clock advances 30 minutes per case to renew shared search stock.',results},null,2));console.log(JSON.stringify(results))}finally{await browser.close()}
