import {chromium} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';import {readFile,mkdir,writeFile} from 'node:fs/promises';
const base='http://127.0.0.1:8099',out='/tmp/vt-depth3-live';await mkdir(out,{recursive:true});const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const errors=[],steps=[],shots=[];
try{const p=await b.newPage({viewport:{width:393,height:750}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
async function state(){return (await p.request.get(base+'/api/state')).json();}async function post(path,data){const s=await state();const r=await p.request.post(base+path,{data:{...data,csrf_token:s.csrf_token}});if(!r.ok())throw Error(path+':'+await r.text());return r.json();}async function act(id,target){const s=await post('/api/action',{id,target,request_id:crypto.randomUUID()});steps.push({id,target,room:s.room.id,scene:s.scene});return s;}
await post('/api/account/register',{username:'visual'+Date.now(),password:'temporary-browser-review-only'});const created=await post('/api/character/create',{name:'Recorrido visual independiente',species:'felaryn',class_id:'sombra'});await post('/api/master/login',{password:'isolated-review-only'});await post('/api/master/approve',{character_id:created.character.id});await act('mover','salir');
const rooms={};for(const region of ['edran','veyra','hoshai','korven','lethra','nhal'])Object.assign(rooms,JSON.parse(await readFile('content/regions/'+region+'.json','utf8')).rooms);
async function walk(dest){let s=await state();const q=[[s.room.id,[]]],seen=new Set([s.room.id]);let path;for(let i=0;i<q.length;i++){const [here,list]=q[i];if(here===dest){path=list;break;}for(const [dir,to]of Object.entries(rooms[here].exits))if(!seen.has(to)){seen.add(to);q.push([to,[...list,dir]]);}}if(!path)throw Error('unreachable '+dest);for(const dir of path){s=await state();if(s.actions.find(a=>a.id==='mover'&&a.target===dir)?.disabled){const permit=s.actions.find(a=>a.id.startsWith('pedir_permiso'));await act(permit.id,permit.target);}await act('mover',dir);}}
await walk('edran_bajo_humedo');await act('examinar_criatura','mordelinde');await walk('lethra_juncal_abierto');await act('examinar_criatura','pinzajunco');await walk('narevia_centro');await walk('nhal_suelo_hojas');await walk('velmora_centro');await walk('valdren_plaza');await p.reload();await p.getByRole('button',{name:'Mapa',exact:true}).click();await p.getByText('Mapa 3D',{exact:true}).click();await p.waitForTimeout(2000);await p.screenshot({path:out+'/debug-initial.png'});console.log(await p.locator('.visual-3d').innerText());await p.locator('.visual-3d canvas').waitFor();
for(const width of [320,393,1440]){await p.setViewportSize({width,height:width===1440?1000:750});await p.waitForTimeout(200);await p.screenshot({path:out+'/map'+width+'.png',fullPage:true});shots.push('map'+width);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('overflow '+width);}
const initial=await state();const labels=p.locator('.visual-3d button').filter({hasText:'Aquí'});if(!await labels.count())throw Error('current label missing');await p.getByRole('button',{name:'Acercar mapa 3D',exact:true}).click();await p.getByRole('button',{name:'Rotar mapa 3D',exact:true}).click();const cb=await p.locator('.visual-3d canvas').boundingBox();await p.mouse.move(cb.x+cb.width*.5,cb.y+cb.height*.5);await p.mouse.down();await p.mouse.move(cb.x+cb.width*.6,cb.y+cb.height*.55,{steps:5});await p.mouse.up();await p.screenshot({path:out+'/rotated-panned.png'});await p.getByRole('button',{name:'Centrar mapa 3D',exact:true}).click();let visible=p.locator('.visual-3d button').filter({hasText:/Plaza|Patio|Mercado|Claro/});for(let i=0;i<await visible.count();i++)if(await visible.nth(i).isVisible()&&!((await visible.nth(i).innerText()).includes('Aquí'))){await visible.nth(i).click();break;}if((await state()).room.id!==initial.room.id)throw Error('select moved player');await p.locator('#map-destination').selectOption('narevia_centro');if((await state()).room.id!==initial.room.id)throw Error('planner selection moved');if(!await p.getByRole('button',{name:/Dar siguiente paso/}).count())throw Error('planner manual move missing');await p.getByRole('button',{name:/Dar siguiente paso/}).click();await p.waitForTimeout(250);if((await state()).room.id===initial.room.id)throw Error('Manual planner step failed');
await p.getByRole('button',{name:'Personaje',exact:true}).click();await p.getByRole('button',{name:/Ver representación de/}).click();await p.locator('dialog').getByText('Ver miniatura 3D',{exact:true}).click();await p.locator('dialog canvas').waitFor();await p.setViewportSize({width:320,height:750});await p.screenshot({path:out+'/felaryn320.png'});await p.keyboard.press('Escape');await p.locator('dialog').waitFor({state:'detached'});
await p.getByRole('button',{name:'Bestiario',exact:true}).click();for(const name of ['Mordelinde','Pinzajunco']){await p.getByRole('button',{name:'Ver imagen de '+name,exact:true}).click();await p.locator('dialog').getByText('Ver miniatura 3D',{exact:true}).click();await p.locator('dialog canvas').waitFor();await p.waitForTimeout(200);await p.screenshot({path:out+'/'+name+'.png'});await p.getByRole('button',{name:'Cerrar',exact:true}).click();await p.locator('dialog').waitFor({state:'detached'});}
await writeFile(out+'/journey.json',JSON.stringify(steps,null,2));console.log('Real journey',steps.length);await p.getByRole('button',{name:'Mapa',exact:true}).click();if(!await p.locator('.visual-3d canvas').count())await p.getByText('Mapa 3D',{exact:true}).click();await p.locator('.visual-3d canvas').waitFor();const lost=await p.locator('.visual-3d canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2')||canvas.getContext('webgl');const ext=gl?.getExtension('WEBGL_lose_context');if(ext){ext.loseContext();return true;}return false;});if(lost){await p.getByText(/La vista 3D se interrumpió/).waitFor();await p.screenshot({path:out+'/contextlost.png'});if(!await p.locator('.discovered-place:visible').count())throw Error('contextlost missing fallback');}
await writeFile(out+'/report.json',JSON.stringify({steps:steps.length,movement:steps.filter(s=>s.id==='mover').length,knownNodes:(await state()).map.nodes.length,bestiary:(await state()).bestiary.map(e=>e.id),errors,selectionDoesNotMove:true,manualPlannerPresent:true,contextLostProvoked:lost,manualPlannerMoved:true,panExercised:true},null,2));await writeFile(out+'/journey.json',JSON.stringify(steps,null,2));console.log(JSON.stringify({out,steps:steps.length,errors}));
}finally{await b.close();}
