import {chromium} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {writeFile,readFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']}),results=[];
try{for(const width of [1440,393,320]){
 const context=await browser.newContext({viewport:{width,height:900}}),calls=[],dialogs=[],errors=[];
 let lost=false,replay=false;
 const character={id:3,name:'Alivision',species:'marevyn',class_id:'artifice',level:1,xp:0,xp_next:100,hp:40,hp_max:100,fatigue:3,seals:2,pa:0,pp:0,attributes:{fuerza:10},equipment:{},portrait:'/client/art/players/alivision-anime-nivel-1-v1.webp'};
 const sheet=()=>({authenticated:true,csrf_token:'fixture',character,inventory:[{id:'ration',name:'Ración',quantity:2}],quests:[{name:'Un encargo',summary:'Entrega una herramienta.'}],room:{name:'Plaza'},catalog:[{id:'ration',name:'Ración',kind:'consumable'}],destinations:[{id:'plaza',name:'Plaza',region:'lethra'}],portraits:[{id:'/client/art/players/alivision-anime-nivel-1-v1.webp',name:'alivision-anime-nivel-1-v1'},{id:'/client/art/players/senku-anime-nivel-1-v1.webp',name:'senku-anime-nivel-1-v1'}],grants:[{id:1,item_id:'ration',item_name:'Ración',amount:2,remaining:2}],history:[{operation:'item',label:'Regalo de raciones',at:1791420000}]});
 await context.route('**/client/art/players/**',async route=>{const file=new URL(route.request().url()).pathname.split('/').pop();assert.match(file,/^[a-z0-9-]+\.webp$/);await route.fulfill({contentType:'image/webp',body:await readFile(`client/art/players/${file}`)});});
 await context.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/master/state')return route.fulfill({json:{authenticated:true,csrf_token:'fixture',pending:[],approved:[character]}});if(path==='/api/master/character/3')return route.fulfill({json:sheet()});if(path==='/api/master/character/manage'){const body=route.request().postDataJSON();calls.push(body);if(lost){lost=false;replay=true;return route.abort('failed');}if(body.operation==='xp'){character.xp+=body.amount;character.level=2;}if(body.operation==='portrait')character.portrait=body.target;return route.fulfill({json:{...sheet(),message:'Cambio aplicado.',replayed:replay}});}return route.fulfill({json:{authenticated:false,csrf_token:'fixture'}})});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));let accept=true;page.on('dialog',async d=>{dialogs.push(d.message());await(accept?d.accept():d.dismiss())});
 await page.goto('http://127.0.0.1:8083/dm');await page.getByRole('button',{name:'Ver jugador Alivision',exact:true}).click();await page.getByRole('button',{name:'Ampliar imagen actual de Alivision',exact:true}).waitFor();await page.getByText('Imagen personal actual',{exact:true}).waitFor();await page.locator('.master-current-portrait img').evaluate(async img=>{await img.decode();if(!img.naturalWidth)throw Error('Broken current portrait');});await page.locator('.master-current-portrait').screenshot({path:`review/ui/dm-management/current-portrait-${width}.png`});await page.getByText('Gestionar personaje',{exact:true}).click();await page.getByText('Conceder experiencia y sellos',{exact:true}).waitFor();await page.getByText('Nivel 1 · Marevyn · Artífice',{exact:true}).waitFor();
 await page.getByText('Ficha, equipo y misiones',{exact:true}).click();await page.getByText('Ración · 2',{exact:true}).waitFor();
 await page.getByText('Conceder experiencia y sellos',{exact:true}).click();const xp=page.locator('form').filter({has:page.getByRole('button',{name:'Conceder XP',exact:true})});await xp.locator('input').fill('50');accept=false;await xp.getByRole('button').click();assert.equal(calls.length,0);accept=true;await xp.getByRole('button').click();await page.getByRole('status').filter({hasText:'Cambio aplicado.'}).waitFor();assert.equal(calls[0].amount,50);assert.equal(calls[0].confirmed,true);assert.match(dialogs.at(-1),/Alivision/);assert.equal(await page.locator('[data-master-character="3"]').getAttribute('open'),'');
 await page.getByText('Regalar objetos',{exact:true}).click();const item=page.locator('form').filter({has:page.getByRole('button',{name:'Entregar objeto',exact:true})});await item.locator('input').fill('2');lost=true;await item.getByRole('button').click();await page.getByRole('button',{name:'Comprobar el cambio pendiente'}).waitFor();assert.equal(await page.getByRole('button',{name:'Conceder XP',exact:true}).isDisabled(),true);const originalId=calls[1].request_id;assert.equal(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('vt-new:master-pending')).request_id),originalId);await page.reload();await page.getByRole('button',{name:'Comprobar el cambio pendiente'}).waitFor();await page.getByText('Conceder experiencia y sellos',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Conceder XP',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Comprobar el cambio pendiente'}).click();await page.getByRole('status').filter({hasText:'Cambio aplicado.'}).waitFor();assert.equal(calls[1].request_id,calls[2].request_id);assert.equal(await page.evaluate(()=>sessionStorage.getItem('vt-new:master-pending')),null);assert.equal(calls[2].amount,2);
 for(const [summary,buttonName,operation] of [['Curar o revivir','Curar en este lugar','heal'],['Trasladar personaje','Trasladar','travel'],['Actualizar imagen personal','Usar imagen','portrait'],['Corregir una entrega de objetos','Retirar de esa entrega','remove_item']]){await page.getByText(summary,{exact:true}).click();if(operation==='portrait'){assert.equal(await page.locator('form').filter({has:page.getByRole('button',{name:'Usar imagen',exact:true})}).locator('select').count(),0);assert.equal(await page.getByRole('radio',{name:/senku/}).count(),0);await page.getByText('Otras imágenes disponibles',{exact:true}).click();await page.getByRole('radio',{name:'senku · Nivel 1 · Cuerpo completo · Versión 1',exact:true}).check();await page.locator('.master-portrait-gallery img').evaluateAll(async imgs=>{for(const img of imgs){if(img.getClientRects().length){await img.decode();if(!img.naturalWidth)throw Error('Broken visible gallery image');}}});await page.locator('details').filter({has:page.locator('summary').filter({hasText:'Actualizar imagen personal'})}).last().screenshot({path:`review/ui/dm-management/portrait-gallery-${width}.png`});}await page.getByRole('button',{name:buttonName,exact:true}).click();await page.getByRole('status').filter({hasText:'Cambio aplicado.'}).waitFor();assert.equal(calls.at(-1).operation,operation);if(operation==='portrait')assert.equal(calls.at(-1).target,'/client/art/players/senku-anime-nivel-1-v1.webp');if(operation==='remove_item')assert.equal(calls.at(-1).target,1);}
 await page.getByText('Historial del DM',{exact:true}).click();await page.getByText(/Regalo de raciones/).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 results.push({width,confirmCancellationNoPost:true,normalXpPayload:true,retainsManagementPanel:true,networkRetrySameRequestId:true,pendingIntentSurvivesReload:true,pendingStorageClearedAfterSuccess:true,otherChangesBlockedUntilRetry:true,healTravelPortraitCorrection:true,currentPortraitVisible:true,currentAndGalleryImagesDecoded:true,portraitThumbnailRadios:true,otherPlayerImagesCollapsed:true,fichaAndHistory:true,noOverflow:true,noBrowserErrors:true});await context.close();
}
 const context=await browser.newContext({viewport:{width:320,height:900}}),players=Array.from({length:31},(_,i)=>({id:i+1,name:`Jugador ${String(i+1).padStart(2,'0')}`,account:`cuenta${i+1}`,species:'marevyn',class_id:'artifice',level:1,blocked:i===29}));
 await context.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/master/state')return route.fulfill({json:{authenticated:true,csrf_token:'fixture',pending:[players[30]],approved:players.slice(0,30)}});return route.fulfill({json:{authenticated:false,csrf_token:'fixture'}})});
 const page=await context.newPage();await page.goto('http://127.0.0.1:8083/dm');assert.equal(await page.getByRole('button',{name:/Ver jugador /}).count(),12);await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByText('Página 2 de 3',{exact:true}).waitFor();const selectedName=await page.getByRole('button',{name:/Ver jugador /}).first().getAttribute('aria-label');await page.getByRole('button',{name:selectedName,exact:true}).click();assert.equal(await page.getByRole('button',{name:/Ver jugador /}).count(),0);assert.equal(await page.getByText('Cambiar contraseña de la cuenta',{exact:true}).count(),1);await page.getByRole('button',{name:'Volver a jugadores',exact:true}).click();await page.getByText('Página 2 de 3',{exact:true}).waitFor();await page.getByRole('searchbox',{name:'Buscar jugadores'}).fill('cuenta30');assert.equal(await page.getByRole('button',{name:/Ver jugador /}).count(),1);await page.getByRole('button',{name:'Ver jugador Jugador 30',exact:true}).click();await page.getByRole('button',{name:'Volver a jugadores',exact:true}).click();assert.equal(await page.getByRole('searchbox',{name:'Buscar jugadores'}).inputValue(),'cuenta30');await page.getByRole('searchbox',{name:'Buscar jugadores'}).fill('');await page.getByRole('combobox',{name:'Filtrar jugadores'}).selectOption('pending');assert.equal(await page.getByRole('button',{name:/Ver jugador /}).count(),1);await page.getByRole('button',{name:'Ver jugador Jugador 31',exact:true}).click();await page.getByRole('button',{name:'Aprobar personaje',exact:true}).waitFor();assert.equal(await page.getByText('Gestionar personaje',{exact:true}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await context.close();results.push({width:320,manyPlayers:31,pagination12:true,searchByAccount:true,backPreservesPageAndSearch:true,onlySelectedControls:true,pendingSubmenu:true,noOverflow:true});
 await writeFile('review/ui/dm-management/browser.json' ,JSON.stringify({scope:'Actual renderer in Chrome with controlled API fixtures. No real player mutations. Player art routes fulfill actual workspace WebP bytes because local server has stale asset whitelist; production asset serving checked separately. All visible portrait/gallery images decoded before screenshots. Tests response-loss replay by aborting the first grant request.',results},null,2));console.log(JSON.stringify(results));}finally{await browser.close()}
