import {chromium,request} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';
import {spawn} from 'node:child_process';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
const data=await mkdtemp(join(tmpdir(),'vt-dm-integration-')),port=8127,base=`http://127.0.0.1:${port}`;
const server=spawn('python3',['-u','-c',"from server.app import create_app;from werkzeug.security import generate_password_hash;import os;app=create_app({'TESTING':True,'DATA_DIR':os.environ['VT_REVIEW_DATA'],'DM_PASSWORD_HASH':generate_password_hash('isolated-director-password')});app.run(host='127.0.0.1',port=8127,use_reloader=False)"],{env:{...process.env,PYTHONPATH:'runtime/python-deps',VT_REVIEW_DATA:data},stdio:'ignore'});
let browser;const results=[];
try{let ready=false;for(let i=0;i<80;i++){try{if((await fetch(base)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(ready,'isolated server ready');browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
for(const width of [393,1440]){
 const player=await request.newContext({baseURL:base});const post=async(path,body)=>{const token=(await(await player.get('/api/state')).json()).csrf_token;return (await player.post(path,{data:{...body,csrf_token:token}}));};
 assert.equal((await post('/api/account/register',{username:`review${width}`,password:'isolated-player-password'})).status(),201);const created=await(await post('/api/character/create',{name:`Review${width}`,species:'marevyn',class_id:'artifice'})).json();const id=created.character.id;
 const context=await browser.newContext({viewport:{width,height:900}});const page=await context.newPage();await page.goto(base+'/dm');await page.getByLabel('Contraseña del director').fill('isolated-director-password');await page.getByRole('button',{name:'Entrar como director'}).click();await page.getByRole('button',{name:`Ver jugador Review${width}`,exact:true}).click();const tile=page.locator('main');await tile.getByRole('button',{name:'Aprobar personaje',exact:true}).click();await tile.getByText('Gestionar personaje',{exact:true}).click();await tile.getByText('Conceder experiencia y sellos',{exact:true}).waitFor();page.on('dialog',d=>d.accept());
 await tile.getByText('Conceder experiencia y sellos',{exact:true}).click();const xp=tile.locator('form').filter({has:page.getByRole('button',{name:'Conceder XP',exact:true})});await xp.locator('input').fill('298');await xp.getByRole('button').click();await page.getByRole('status').filter({hasText:'298 XP'}).waitFor();let state=await(await player.get('/api/state')).json();assert.equal(state.character.level,3);assert.equal(state.character.xp,80);assert.equal(state.character.pa,4);
 await tile.getByText('Regalar objetos',{exact:true}).click();const item=tile.locator('form').filter({has:page.getByRole('button',{name:'Entregar objeto',exact:true})});await item.locator('select').selectOption('provision_basica');await item.locator('input').fill('2');await item.getByRole('button').click();await page.getByRole('status').filter({hasText:'2 × Provisión'}).waitFor();state=await(await player.get('/api/state')).json();assert.equal(state.inventory.filter(i=>i.catalog_id==='provision_basica').reduce((n,i)=>n+i.quantity,0),2);
 await tile.getByText('Corregir una entrega de objetos',{exact:true}).click();await tile.getByRole('button',{name:'Retirar de esa entrega'}).click();await page.getByRole('status').filter({hasText:'retira 1'}).waitFor();state=await(await player.get('/api/state')).json();assert.equal(state.inventory.filter(i=>i.catalog_id==='provision_basica').reduce((n,i)=>n+i.quantity,0),1);
 await tile.getByText('Actualizar imagen personal',{exact:true}).click();const portrait=tile.locator('form').filter({has:page.getByRole('button',{name:'Usar imagen',exact:true})});const option=portrait.locator('input[type=radio][value="/client/art/players/alivision-anime-nivel-1-v1.webp"]');if(!(await option.isVisible()))await portrait.getByText('Otras imágenes disponibles',{exact:true}).click();await option.check();await portrait.getByRole('button').click();await page.getByRole('status').filter({hasText:'imagen personalizada'}).waitFor();state=await(await player.get('/api/state')).json();assert.equal(state.character.portrait,'/client/art/players/alivision-anime-nivel-1-v1.webp');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));results.push({width,realApiXpAndLevels:true,realApiGiftAndCorrection:true,realApiPortrait:true,noOverflow:true});await context.close();await player.dispose();}
await writeFile('review/ui/dm-management/integration.json',JSON.stringify({scope:'Actual Flask API, production content and browser renderer with fresh temporary SQLite and invented review credentials. No production writes.',results},null,2));console.log(results);
}finally{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));await rm(data,{recursive:true,force:true});}
