import {chromium} from '/tmp/vt-new-browser-tools/node_modules/playwright/index.mjs';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const snapshot=JSON.parse(await readFile('/tmp/vt-desktop-map-state.json','utf8')),before=process.env.VT_MAP_BASELINE==='1',results=[],browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
try{for(const width of [1440,393,320]){const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/state',r=>r.fulfill({json:snapshot}));await page.goto('http://127.0.0.1:8083');await page.getByRole('button',{name:'Mapa',exact:true}).click();await page.getByRole('button',{name:'Ver todo lo descubierto',exact:true}).click();await page.waitForTimeout(250);
 const overview=await page.locator('.discovered-scroll').evaluate(view=>{const clip=view.getBoundingClientRect(),nodes=[...view.querySelectorAll('.discovered-place')];return {total:nodes.length,fullyVisible:nodes.filter(node=>{const r=node.getBoundingClientRect();return r.left>=clip.left-1&&r.top>=clip.top-1&&r.right<=clip.right+1&&r.bottom<=clip.bottom+1}).length,scale:Number(view.dataset.scale)}});
 assert.equal(overview.total,snapshot.map.nodes.length);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:`review/map-overview/${before?'before':'after'}-${width}.png`});
 if(!before){assert.equal(overview.fullyVisible,overview.total);const scale=overview.scale;await page.getByRole('button',{name:'Acercar mapa',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Acercar mapa');await page.waitForTimeout(100);assert.ok(Number(await page.locator('.discovered-scroll').getAttribute('data-scale'))>scale);await page.getByRole('button',{name:'Alejar mapa',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Alejar mapa');await page.getByRole('button',{name:'Ver todo lo descubierto',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Ver todo lo descubierto');await page.setViewportSize({width,height:700});await page.waitForTimeout(100);assert.equal(await page.locator('.discovered-scroll').evaluate(view=>{const c=view.getBoundingClientRect();return [...view.querySelectorAll('.discovered-place')].filter(n=>{const r=n.getBoundingClientRect();return r.left>=c.left-1&&r.top>=c.top-1&&r.right<=c.right+1&&r.bottom<=c.bottom+1}).length}),snapshot.map.nodes.length);await page.getByRole('button',{name:'Volver a tu posición',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Volver a tu posición');assert.equal(await page.locator('.discovered-current').count(),1);assert.ok(await page.locator('.discovered-place').count()<snapshot.map.nodes.length);assert.equal(Number(await page.locator('.discovered-scroll').getAttribute('data-scale')),1)}
 results.push({width,...overview,errors});await page.close()}
 await writeFile(`review/map-overview/${before?'before':'after'}.json`,JSON.stringify({scope:'Read-only saved discovered map snapshot: 110 known places, no player actions. Real Chrome desktop/mobile viewport emulation.',results},null,2));console.log(JSON.stringify(results))}finally{await browser.close()}
